### PR TITLE
Signin page

### PR DESCRIPTION
**Pull request by Kevin-D23**

### CODE REVIEW

**Review by tomli380576 — APPROVED** [review]
Looks good!

**Review by jackie-ou — CHANGES_REQUESTED** [review]
```  
 <style>{`body {
                margin: 0;
            }`}</style>
 ```
Consider not using inline css by setting a className and then targeting that for margin 0

Putting margin: 0 for the container doesn't solve my issue (of making the page static/unscrollable) because the body still holds a default margin. So would this be something that should be globally declared?

**Comment by Kevin-D23** [comment]
> ```
> <style>{`body {
>              margin: 0;
>          }`}</style>
> ```
> 
> Consider not using inline css by setting a className and then targeting that for margin 0

Putting margin: 0 for the container doesn't solve my issue (of making the page static/unscrollable) because the body still holds a default margin. So would this be something that should be globally declared?

**Review by jackie-ou — APPROVED** [review]
Nice job

**Pull request merged**
